# Site settings
title: JJasonClark.com
email: jason@jjasonclark.com
description: > # this means to ignore newlines until "baseurl:"
  Stuff I have time to write about
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jjasonclark.com" # the base hostname & protocol for your site
twitter_username: jjasonclark
github_username:  jjasonclark
timezone: America/Vancouver
encoding: utf-8
google_analytics_code: UA-12083278-1
disqus_shortname: jjasonclark
exclude: [README.md, Rakefile, Gemfile, Gemfile.lock, Procfile, vendor]

# Build settings
markdown: kramdown
permalink: /:title

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: Jason Clark
      gplus: https://plus.google.com/117263003751658777941
